[build]
  command = "pip install --upgrade pip && pip install -r requirements.txt"

[build.environment]
  PYTHON_VERSION = "3.10"
  PIP_NO_CACHE_DIR = "off"
  FORCE_COLOR = "1"
  PIP_EXTRA_INDEX_URL = "https://pypi.org/simple"

[[plugins]]
  package = "@netlify/plugin-local-install"